// ...existing code...
module.exports = {
  // ...existing code...
  images: {
    domains: ['www.megapixl.com', 'via.placeholder.com', 'placebear.com', 'res.cloudinary.com'],
  },
};
// ...existing code...
